#!/usr/bin/env ruby

require_relative '../lib/generator'

EXAMPLE_CONFIG_FILE = 'config/router.fqdn.example.yml'

Dir.chdir(CURRENT_DIRECTORY) do
  Dir.glob("config/*.yml").each do |config_file|
    next if ARGV[0] == '--skip-example-config' && config_file == EXAMPLE_CONFIG_FILE

    Dir.glob("templates/{[!_]*}.erb").each do |template_file|
      new_filename = template_file.split('/').last.gsub('.erb', '')

      out_directory_name = config_file.split('/').last.gsub('.yml', '')
      out_directory_path = "#{File.dirname(__dir__)}/out/#{out_directory_name}/"
      FileUtils.mkdir_p(out_directory_path)

      configuration = Configuration.from_yaml(config_file)
      helper = Helpers::Peers.new(configuration)
      computed_template = render(template_file.split('/').last, helper)

      File.write("#{out_directory_path}/#{new_filename}", computed_template)
    end
  end
end
